databases:
  - name: bugdetapp
    databaseName: bugdetapp
    user: bugdetapp_user

services:
  - type: web
    name: yashbudgetapp
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bugdetapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false